# Generated by Django 5.0.6 on 2024-07-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_datos', models.DateField()),
                ('posicion', models.IntegerField()),
                ('mejor_vuelta', models.DurationField()),
                ('auto_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedad.auto_modelo')),
            ],
        ),
    ]
